// ============ CONTENT SCRIPT - AUTOFILL SUPPORT ============
// Detects password fields and suggests strong passwords
// Also handles autofill from saved passwords
// Auto-generates passwords on signup pages

function generateStrongPassword() {
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()_+~|}{[]:;?><,./-=';
    const array = new Uint32Array(20);
    window.crypto.getRandomValues(array);
    let pwd = '';
    for (let i = 0; i < array.length; i++) {
        pwd += chars[array[i] % chars.length];
    }
    return pwd;
}

// Detect if current page is a signup/register form
function isSignupPage() {
    const url = window.location.href.toLowerCase();
    const html = document.documentElement.innerHTML.toLowerCase();
    
    // Check URL patterns
    const signupPatterns = [/signup|register|join|create.*account|new.*account|sign.*up|enroll/];
    const isSignupUrl = signupPatterns.some(p => p.test(url));
    
    // Check for password confirmation field (strong indicator of signup)
    const hasConfirmPassword = Array.from(document.querySelectorAll('input[type="password"]')).length > 1 ||
                               html.includes('confirm password') || 
                               html.includes('repeat password') ||
                               html.includes('password again');
    
    // Check for signup-related text in page
    const signupText = [/sign up|register|create account|join now|get started/];
    const hasSignupText = signupText.some(p => p.test(html));
    
    return isSignupUrl || (hasConfirmPassword && hasSignupText);
}

let activeInput = null;
let suggestionBox = null;
let autoGeneratedPassword = null;

function createSuggestionBox() {
    if (suggestionBox) return;
    suggestionBox = document.createElement('div');
    suggestionBox.id = 'openlock-suggestion-box';
    suggestionBox.style.cssText = `
        position: absolute;
        z-index: 2147483647;
        background: #1e1e24;
        border: 1px solid #3a3a45;
        border-radius: 8px;
        padding: 12px;
        box-shadow: 0 4px 12px rgba(0,0,0,0.3);
        display: none;
        font-family: system-ui, -apple-system, sans-serif;
        color: #fff;
        width: 280px;
        min-width: 250px;
    `;

    const title = document.createElement('div');
    title.textContent = 'OpenLock';
    title.style.cssText = `
        font-size: 12px;
        color: #888;
        margin-bottom: 8px;
        font-weight: 600;
        letter-spacing: 0.5px;
    `;

    const message = document.createElement('div');
    message.id = 'op-form-context';
    message.textContent = 'Detected Password Field';
    message.style.cssText = `
        font-size: 14px;
        margin-bottom: 8px;
        color: #eee;
    `;

    const suggestBtn = document.createElement('button');
    suggestBtn.id = 'op-suggest-btn';
    suggestBtn.textContent = isSignupPage() ? 'Auto-Generate New Password' : 'Generate Strong Password';
    suggestBtn.style.cssText = `
        background: #3b82f6;
        color: #fff;
        border: none;
        border-radius: 4px;
        padding: 8px 12px;
        width: 100%;
        cursor: pointer;
        font-weight: bold;
        margin-bottom: 8px;
        transition: background 0.2s;
        font-size: 13px;
    `;

    suggestBtn.onmouseover = () => suggestBtn.style.background = '#2563eb';
    suggestBtn.onmouseout = () => suggestBtn.style.background = '#3b82f6';

    suggestBtn.addEventListener('click', (e) => {
        e.preventDefault();
        e.stopPropagation();
        if (activeInput) {
            const newPwd = generateStrongPassword();
            autoGeneratedPassword = newPwd;
            activeInput.value = newPwd;
            activeInput.dispatchEvent(new Event('input', { bubbles: true }));
            activeInput.dispatchEvent(new Event('change', { bubbles: true }));
            
            // Find and fill confirm password field (on signup pages)
            if (activeInput.form) {
                const pwds = Array.from(activeInput.form.querySelectorAll('input[type="password"]'));
                pwds.forEach(p => {
                    if (p !== activeInput) {
                        p.value = newPwd;
                        p.dispatchEvent(new Event('input', { bubbles: true }));
                        p.dispatchEvent(new Event('change', { bubbles: true }));
                    }
                });
            }
            
            // Auto-save to vault via background
            chrome.runtime.sendMessage({
                type: 'savePendingPassword',
                password: newPwd,
                website: window.location.hostname
            }).catch(e => console.log('Extension not ready'));
            
            suggestionBox.style.display = 'none';
        }
    });

    const autofillBtn = document.createElement('button');
    autofillBtn.textContent = '🔐 Autofill from Vault';
    autofillBtn.style.cssText = `
        background: #10b981;
        color: #fff;
        border: none;
        border-radius: 4px;
        padding: 8px 12px;
        width: 100%;
        cursor: pointer;
        font-weight: bold;
        transition: background 0.2s;
        font-size: 13px;
    `;

    autofillBtn.onmouseover = () => autofillBtn.style.background = '#059669';
    autofillBtn.onmouseout = () => autofillBtn.style.background = '#10b981';

    autofillBtn.addEventListener('click', (e) => {
        e.preventDefault();
        e.stopPropagation();
        chrome.runtime.sendMessage({
            type: 'openAutofill',
            domain: window.location.hostname
        }).catch(e => console.log('Extension not ready'));
    });

    suggestionBox.appendChild(title);
    suggestionBox.appendChild(message);
    suggestionBox.appendChild(suggestBtn);
    suggestionBox.appendChild(autofillBtn);

    document.body.appendChild(suggestionBox);
}

function positionSuggestionBox(input) {
    if (!suggestionBox) return;

    const rect = input.getBoundingClientRect();
    const boxHeight = 140;
    const boxWidth = 280;

    let top = rect.bottom + window.scrollY + 5;
    let left = rect.left + window.scrollX;

    // Adjust if box goes off-screen
    if (top + boxHeight > window.innerHeight + window.scrollY) {
        top = rect.top + window.scrollY - boxHeight - 5;
    }

    if (left + boxWidth > window.innerWidth) {
        left = window.innerWidth - boxWidth - 10;
    }

    suggestionBox.style.top = top + 'px';
    suggestionBox.style.left = left + 'px';
}

function showSuggestion(input) {
    createSuggestionBox();
    activeInput = input;
    positionSuggestionBox(input);
    suggestionBox.style.display = 'block';
}

function hideSuggestion() {
    if (suggestionBox) {
        suggestionBox.style.display = 'none';
    }
}

// Detect password and login fields
document.addEventListener('focus', (e) => {
    if (e.target.type === 'password') {
        showSuggestion(e.target);
        
        // On signup pages, auto-generate password if not already set
        if (isSignupPage() && !e.target.value && !autoGeneratedPassword) {
            setTimeout(() => {
                const suggestBtn = document.getElementById('op-suggest-btn');
                if (suggestBtn) {
                    suggestBtn.click();
                }
            }, 100);
        }
    }
}, true);

document.addEventListener('blur', (e) => {
    if (e.target.type === 'password') {
        setTimeout(hideSuggestion, 200);
    }
}, true);

// Handle clicks outside
document.addEventListener('click', (e) => {
    if (e.target !== suggestionBox && !suggestionBox?.contains(e.target)) {
        hideSuggestion();
    }
}, true);

// Detect username/email fields and add context
document.addEventListener('focus', (e) => {
    if (e.target.type === 'email' || e.target.type === 'text') {
        const name = (e.target.name || e.target.id || '').toLowerCase();
        if (name.includes('email') || name.includes('user') || name.includes('login')) {
            if (suggestionBox && suggestionBox.style.display === 'block') {
                const context = document.getElementById('op-form-context');
                if (context) {
                    context.textContent = `Form: ${window.location.hostname}`;
                }
            }
        }
    }
}, true);

// Handle form submission - offer to save
document.addEventListener('submit', (e) => {
    const form = e.target;
    const passwordInputs = form.querySelectorAll('input[type="password"]');
    
    if (passwordInputs.length > 0) {
        const password = passwordInputs[0].value;
        if (password && password.length > 6) {
            chrome.runtime.sendMessage({
                type: 'formSubmitted',
                website: window.location.hostname,
                password: password,
                title: document.title
            }).catch(e => console.log('Extension not ready'));
        }
    }
}, true);

// Listen for autofill requests from extension
chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
    if (request.type === 'autofillPassword') {
        const passwordInputs = document.querySelectorAll('input[type="password"]');
        passwordInputs.forEach(input => {
            input.value = request.password;
            input.dispatchEvent(new Event('input', { bubbles: true }));
            input.dispatchEvent(new Event('change', { bubbles: true }));
        });
        sendResponse({ success: true });
    }
});

// Initialize on page load - if signup page, show autofill banner
function initializeOnPageLoad() {
    if (isSignupPage()) {
        // Show a banner when page loads on signup
        const banner = document.createElement('div');
        banner.id = 'openlock-banner';
        banner.style.cssText = `
            position: fixed;
            top: 0;
            left: 0;
            right: 0;
            background: linear-gradient(135deg, #3b82f6 0%, #2563eb 100%);
            color: white;
            padding: 12px 20px;
            font-family: system-ui, -apple-system, sans-serif;
            font-size: 14px;
            z-index: 2147483646;
            display: flex;
            justify-content: space-between;
            align-items: center;
            box-shadow: 0 2px 8px rgba(0,0,0,0.2);
        `;
        
        const text = document.createElement('span');
        text.textContent = '🔐 OpenLock - Password will be auto-generated on this signup form';
        text.style.cssText = 'flex: 1;';
        
        const closeBtn = document.createElement('button');
        closeBtn.textContent = '✕';
        closeBtn.style.cssText = `
            background: rgba(255,255,255,0.2);
            border: none;
            color: white;
            cursor: pointer;
            padding: 4px 8px;
            border-radius: 4px;
            font-size: 16px;
            transition: background 0.2s;
        `;
        
        closeBtn.onmouseover = () => closeBtn.style.background = 'rgba(255,255,255,0.3)';
        closeBtn.onmouseout = () => closeBtn.style.background = 'rgba(255,255,255,0.2)';
        
        closeBtn.addEventListener('click', () => {
            banner.remove();
        });
        
        banner.appendChild(text);
        banner.appendChild(closeBtn);
        document.body.prepend(banner);
    }
}

// Wait for DOM to be ready
if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', initializeOnPageLoad);
} else {
    initializeOnPageLoad();
}

console.log('OpenLock autofill enabled');
console.log('Signup page detected:', isSignupPage());
