// ============ CONTENT SCRIPT - AUTOFILL SUPPORT ============
// Detects password fields, autofills credentials, and prompts to save

function generateStrongPassword() {
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()_+~|}{[]:;?><,./-=';
    const array = new Uint32Array(20);
    window.crypto.getRandomValues(array);
    let pwd = '';
    for (let i = 0; i < array.length; i++) {
        pwd += chars[array[i] % chars.length];
    }
    return pwd;
}

// Detect if current page is a signup/register form
function isSignupPage() {
    const url = window.location.href.toLowerCase();
    const html = document.documentElement.innerHTML.toLowerCase();
    
    const signupPatterns = [/signup|register|join|create.*account|new.*account|sign.*up|enroll|join.*now/];
    const isSignupUrl = signupPatterns.some(p => p.test(url));
    
    const hasConfirmPassword = Array.from(document.querySelectorAll('input[type="password"]')).length > 1 ||
                               html.includes('confirm password') || 
                               html.includes('repeat password') ||
                               html.includes('password again');
    
    const signupText = [/sign up|register|create account|join now|get started|sign up/];
    const hasSignupText = signupText.some(p => p.test(html));
    
    return isSignupUrl || (hasConfirmPassword && hasSignupText);
}

// Find username or email input fields
function findUsernameField() {
    const inputs = document.querySelectorAll('input[type="email"], input[type="text"], input[name*="user"], input[name*="email"], input[name*="login"]');
    for (let input of inputs) {
        const name = (input.name || input.id || '').toLowerCase();
        const placeholder = (input.placeholder || '').toLowerCase();
        if (name.includes('email') || name.includes('user') || name.includes('login') || 
            placeholder.includes('email') || placeholder.includes('user') || placeholder.includes('username')) {
            return input;
        }
    }
    return inputs[0];
}

let activeInput = null;
let suggestionBox = null;
let autoGeneratedPassword = null;
let showedSuggestion = new Set();

// Create suggestion box UI
function createSuggestionBox() {
    if (suggestionBox) return;
    
    suggestionBox = document.createElement('div');
    suggestionBox.id = 'openlock-suggestion-box';
    suggestionBox.style.cssText = `
        position: absolute;
        z-index: 2147483647;
        background: linear-gradient(135deg, #1a1a2e 0%, #242442 100%);
        border: 1px solid #6366f1;
        border-radius: 12px;
        padding: 14px;
        box-shadow: 0 8px 24px rgba(99, 102, 241, 0.3);
        display: none;
        font-family: 'Inter', system-ui, -apple-system, sans-serif;
        color: #f0f0ff;
        width: 300px;
        min-width: 270px;
    `;

    const title = document.createElement('div');
    title.textContent = '🔐 OpenLock';
    title.style.cssText = `
        font-size: 12px;
        color: #a8a8c8;
        margin-bottom: 10px;
        font-weight: 700;
        letter-spacing: 0.8px;
    `;

    const message = document.createElement('div');
    message.id = 'op-form-context';
    message.textContent = 'Password field detected';
    message.style.cssText = `
        font-size: 13px;
        margin-bottom: 10px;
        color: #f0f0ff;
        font-weight: 500;
    `;

    // Generate password button
    const generateBtn = document.createElement('button');
    generateBtn.id = 'op-generate-btn';
    generateBtn.textContent = isSignupPage() ? '✨ Auto-Generate' : '⚡ Generate Password';
    generateBtn.style.cssText = `
        background: linear-gradient(135deg, #6366f1 0%, #818cf8 100%);
        color: #fff;
        border: none;
        border-radius: 6px;
        padding: 10px 14px;
        width: 100%;
        cursor: pointer;
        font-weight: 600;
        margin-bottom: 8px;
        transition: all 0.3s ease;
        font-size: 13px;
        font-family: inherit;
    `;

    generateBtn.addEventListener('mouseover', () => {
        generateBtn.style.transform = 'translateY(-1px)';
        generateBtn.style.boxShadow = '0 4px 12px rgba(99, 102, 241, 0.3)';
    });
    generateBtn.addEventListener('mouseout', () => {
        generateBtn.style.transform = 'translateY(0)';
        generateBtn.style.boxShadow = 'none';
    });

    generateBtn.addEventListener('click', (e) => {
        e.preventDefault();
        e.stopPropagation();
        
        if (activeInput) {
            const newPwd = generateStrongPassword();
            autoGeneratedPassword = newPwd;
            
            activeInput.value = newPwd;
            activeInput.dispatchEvent(new Event('input', { bubbles: true }));
            activeInput.dispatchEvent(new Event('change', { bubbles: true }));
            
            if (activeInput.form) {
                const pwds = Array.from(activeInput.form.querySelectorAll('input[type="password"]'));
                pwds.forEach(p => {
                    if (p !== activeInput) {
                        p.value = newPwd;
                        p.dispatchEvent(new Event('input', { bubbles: true }));
                        p.dispatchEvent(new Event('change', { bubbles: true }));
                    }
                });
            }
            
            generateBtn.textContent = '✓ Generated!';
            generateBtn.style.background = 'linear-gradient(135deg, #10b981 0%, #059669 100%)';
            setTimeout(() => {
                suggestionBox.style.display = 'none';
            }, 800);
        }
    });

    // Autofill button
    const autofillBtn = document.createElement('button');
    autofillBtn.textContent = '📋 Autofill';
    autofillBtn.style.cssText = `
        background: linear-gradient(135deg, #10b981 0%, #059669 100%);
        color: #fff;
        border: none;
        border-radius: 6px;
        padding: 10px 14px;
        width: 100%;
        cursor: pointer;
        font-weight: 600;
        transition: all 0.3s ease;
        font-size: 13px;
        font-family: inherit;
    `;

    autofillBtn.addEventListener('mouseover', () => {
        autofillBtn.style.transform = 'translateY(-1px)';
        autofillBtn.style.boxShadow = '0 4px 12px rgba(16, 185, 129, 0.3)';
    });
    autofillBtn.addEventListener('mouseout', () => {
        autofillBtn.style.transform = 'translateY(0)';
        autofillBtn.style.boxShadow = 'none';
    });

    autofillBtn.addEventListener('click', (e) => {
        e.preventDefault();
        e.stopPropagation();
        performAutofill();
    });

    suggestionBox.appendChild(title);
    suggestionBox.appendChild(message);
    suggestionBox.appendChild(generateBtn);
    suggestionBox.appendChild(autofillBtn);

    document.body.appendChild(suggestionBox);
}

// Perform autofill from saved passwords
function performAutofill() {
    const domain = window.location.hostname.replace('www.', '');
    
    chrome.runtime.sendMessage({
        type: 'autofillRequest',
        domain: domain
    }, (response) => {
        if (response && response.success) {
            if (response.username) {
                const usernameField = findUsernameField();
                if (usernameField) {
                    usernameField.value = response.username;
                    usernameField.dispatchEvent(new Event('input', { bubbles: true }));
                    usernameField.dispatchEvent(new Event('change', { bubbles: true }));
                }
            }
            
            const passwordInputs = document.querySelectorAll('input[type="password"]');
            passwordInputs.forEach(input => {
                input.value = response.password;
                input.dispatchEvent(new Event('input', { bubbles: true }));
                input.dispatchEvent(new Event('change', { bubbles: true }));
            });
            
            if (suggestionBox) {
                suggestionBox.style.display = 'none';
            }
            showToast('✓ Autofilled!');
        } else {
            showToast('No saved password for this site');
        }
    });
}

// Show toast notification
function showToast(message) {
    const toast = document.createElement('div');
    toast.style.cssText = `
        position: fixed;
        bottom: 20px;
        right: 20px;
        background: linear-gradient(135deg, #10b981 0%, #059669 100%);
        color: white;
        padding: 12px 20px;
        border-radius: 8px;
        font-size: 14px;
        font-weight: 500;
        z-index: 2147483646;
        box-shadow: 0 4px 12px rgba(0, 0, 0, 0.2);
        animation: slideIn 0.3s ease;
    `;
    
    document.body.appendChild(toast);
    setTimeout(() => {
        toast.style.animation = 'slideOut 0.3s ease';
        setTimeout(() => toast.remove(), 300);
    }, 2000);
}

function positionSuggestionBox(input) {
    if (!suggestionBox) return;

    const rect = input.getBoundingClientRect();
    const boxHeight = 160;
    const boxWidth = 300;

    let top = rect.bottom + window.scrollY + 8;
    let left = rect.left + window.scrollX;

    if (top + boxHeight > window.innerHeight + window.scrollY) {
        top = rect.top + window.scrollY - boxHeight - 8;
    }

    if (left + boxWidth > window.innerWidth) {
        left = window.innerWidth - boxWidth - 10;
    }

    if (left < 0) {
        left = 10;
    }

    suggestionBox.style.top = top + 'px';
    suggestionBox.style.left = left + 'px';
}

function showSuggestion(input) {
    createSuggestionBox();
    activeInput = input;
    positionSuggestionBox(input);
    suggestionBox.style.display = 'block';
}

function hideSuggestion() {
    if (suggestionBox) {
        suggestionBox.style.display = 'none';
    }
}

// Listen for password field focus
document.addEventListener('focus', (e) => {
    if (e.target.type === 'password') {
        showSuggestion(e.target);
        
        if (isSignupPage() && !e.target.value && !autoGeneratedPassword) {
            setTimeout(() => {
                const generateBtn = document.getElementById('op-generate-btn');
                if (generateBtn) {
                    generateBtn.click();
                }
            }, 300);
        }
    }
}, true);

// Listen for focus loss
document.addEventListener('blur', (e) => {
    if (e.target.type === 'password') {
        setTimeout(hideSuggestion, 200);
    }
}, true);

// Handle clicks outside suggestion box
document.addEventListener('click', (e) => {
    if (suggestionBox && e.target !== suggestionBox && !suggestionBox?.contains(e.target)) {
        hideSuggestion();
    }
}, true);

// Handle form submission - offer to save
document.addEventListener('submit', (e) => {
    const form = e.target;
    const passwordInputs = form.querySelectorAll('input[type="password"]');
    
    if (passwordInputs.length > 0) {
        const password = passwordInputs[0].value;
        const usernameField = findUsernameField();
        const username = usernameField?.value || '';
        
        if (password && password.length > 6) {
            if (isSignupPage()) {
                e.preventDefault();
                showSavePrompt(password, username, form);
            } else {
                chrome.runtime.sendMessage({
                    type: 'formSubmitted',
                    website: window.location.hostname,
                    password: password,
                    username: username
                }).catch(() => {});
            }
        }
    }
}, true);

// Show save prompt modal
function showSavePrompt(password, username, form) {
    const overlay = document.createElement('div');
    overlay.style.cssText = `
        position: fixed;
        inset: 0;
        background: rgba(0, 0, 0, 0.5);
        display: flex;
        align-items: center;
        justify-content: center;
        z-index: 2147483647;
        backdrop-filter: blur(2px);
    `;

    const modal = document.createElement('div');
    modal.style.cssText = `
        background: linear-gradient(135deg, #1a1a2e 0%, #242442 100%);
        border: 1px solid #6366f1;
        border-radius: 14px;
        padding: 24px;
        max-width: 380px;
        color: #f0f0ff;
        font-family: 'Inter', system-ui, -apple-system, sans-serif;
        box-shadow: 0 20px 60px rgba(0, 0, 0, 0.4);
        animation: slideUp 0.3s ease;
    `;

    const title = document.createElement('h3');
    title.textContent = '💾 Save Password?';
    title.style.cssText = `
        margin: 0 0 8px 0;
        font-size: 18px;
        font-weight: 700;
    `;

    const subtitle = document.createElement('p');
    subtitle.textContent = `Save your credentials for ${window.location.hostname}?`;
    subtitle.style.cssText = `
        margin: 0 0 16px 0;
        font-size: 14px;
        color: #a8a8c8;
    `;

    const buttonsDiv = document.createElement('div');
    buttonsDiv.style.cssText = `
        display: flex;
        gap: 10px;
    `;

    const cancelBtn = document.createElement('button');
    cancelBtn.textContent = 'Skip';
    cancelBtn.style.cssText = `
        flex: 1;
        padding: 10px 16px;
        background: transparent;
        border: 1px solid #6366f1;
        color: #6366f1;
        border-radius: 6px;
        cursor: pointer;
        font-weight: 600;
        font-size: 14px;
        font-family: inherit;
        transition: all 0.3s ease;
    `;

    cancelBtn.addEventListener('click', () => {
        overlay.remove();
        form.submit();
    });

    const saveBtn = document.createElement('button');
    saveBtn.textContent = 'Save & Continue';
    saveBtn.style.cssText = `
        flex: 1;
        padding: 10px 16px;
        background: linear-gradient(135deg, #6366f1 0%, #818cf8 100%);
        border: none;
        color: white;
        border-radius: 6px;
        cursor: pointer;
        font-weight: 600;
        font-size: 14px;
        font-family: inherit;
        transition: all 0.3s ease;
    `;

    saveBtn.addEventListener('click', () => {
        chrome.runtime.sendMessage({
            type: 'savePendingPassword',
            website: window.location.hostname,
            password: password,
            username: username
        }, () => {
            overlay.remove();
            form.submit();
        });
    });

    buttonsDiv.appendChild(cancelBtn);
    buttonsDiv.appendChild(saveBtn);
    modal.appendChild(title);
    modal.appendChild(subtitle);
    modal.appendChild(buttonsDiv);
    overlay.appendChild(modal);
    document.body.appendChild(overlay);
}

// Listen for autofill requests from popup
chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
    if (request.type === 'autofillPassword') {
        const passwordInputs = document.querySelectorAll('input[type="password"]');
        passwordInputs.forEach(input => {
            input.value = request.password;
            input.dispatchEvent(new Event('input', { bubbles: true }));
            input.dispatchEvent(new Event('change', { bubbles: true }));
        });
        sendResponse({ success: true });
    }
});

// Add animation styles to document
const style = document.createElement('style');
style.textContent = `
    @keyframes slideUp {
        from { opacity: 0; transform: translateY(20px); }
        to { opacity: 1; transform: translateY(0); }
    }
    @keyframes slideIn {
        from { opacity: 0; transform: translateX(20px); }
        to { opacity: 1; transform: translateX(0); }
    }
    @keyframes slideOut {
        from { opacity: 1; transform: translateX(0); }
        to { opacity: 0; transform: translateX(20px); }
    }
`;
document.head.appendChild(style);

console.log('✓ OpenLock autofill enabled');
console.log('  Signup page:', isSignupPage());
